import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";
import type { TFunction } from "i18next";
import { AlertCircle, ArrowDown, ArrowUp, Check, CheckCircle2, Crop, Database, Eye, Filter, GripVertical, Image, Layers3, Maximize2, Plus, RefreshCw, RotateCw, Sparkles, Trash2, WandSparkles, X } from "lucide-react";
import { translateBackendError } from "./i18n/errors";
import type { DataNodeCategory, DataPipeline, DataPipelineNode, DatasetSummary, TaskId } from "./types";

type Definition = Omit<DataPipelineNode,"id"|"enabled"> & {modalities:string[];excludeTasks?:TaskId[];unique?:boolean};

const DEFINITIONS:Definition[]=[
  {type:"validate",label:"dataPipeline:definitions.validate.label",description:"dataPipeline:definitions.validate.description",category:"inspect",scope:"all",properties:{fail_on_error:true},modalities:["all"],unique:true},
  {type:"deduplicate",label:"dataPipeline:definitions.deduplicate.label",description:"dataPipeline:definitions.deduplicate.description",category:"curate",scope:"all",properties:{include_target:true},modalities:["all"]},
  {type:"finite_filter",label:"dataPipeline:definitions.finite_filter.label",description:"dataPipeline:definitions.finite_filter.description",category:"curate",scope:"all",properties:{},modalities:["tabular","sequence"]},
  {type:"normalize",label:"dataPipeline:definitions.normalize.label",description:"dataPipeline:definitions.normalize.description",category:"transform",scope:"all",properties:{mode:"standard"},modalities:["tabular","sequence"],unique:true},
  {type:"clip",label:"dataPipeline:definitions.clip.label",description:"dataPipeline:definitions.clip.description",category:"transform",scope:"all",properties:{lower:1,upper:99},modalities:["tabular","sequence"]},
  {type:"resize",label:"dataPipeline:definitions.resize.label",description:"dataPipeline:definitions.resize.description",category:"transform",scope:"all",properties:{width:128,height:128,method:"bilinear"},modalities:["image"],unique:true},
  {type:"center_crop",label:"dataPipeline:definitions.center_crop.label",description:"dataPipeline:definitions.center_crop.description",category:"transform",scope:"all",properties:{width:96,height:96},modalities:["image"]},
  {type:"convert_channels",label:"dataPipeline:definitions.convert_channels.label",description:"dataPipeline:definitions.convert_channels.description",category:"transform",scope:"all",properties:{channels:3},modalities:["image"],unique:true},
  {type:"image_normalize",label:"dataPipeline:definitions.image_normalize.label",description:"dataPipeline:definitions.image_normalize.description",category:"transform",scope:"all",properties:{mode:"standard"},modalities:["image"],unique:true},
  {type:"random_flip",label:"dataPipeline:definitions.random_flip.label",description:"dataPipeline:definitions.random_flip.description",category:"augment",scope:"train",properties:{probability:.5,horizontal:true},modalities:["image"],excludeTasks:["image.regression"]},
  {type:"random_rotate90",label:"dataPipeline:definitions.random_rotate90.label",description:"dataPipeline:definitions.random_rotate90.description",category:"augment",scope:"train",properties:{probability:.35},modalities:["image"],excludeTasks:["image.regression"]},
  {type:"color_jitter",label:"dataPipeline:definitions.color_jitter.label",description:"dataPipeline:definitions.color_jitter.description",category:"augment",scope:"train",properties:{brightness:.15,contrast:.15},modalities:["image"]},
  {type:"random_noise",label:"dataPipeline:definitions.random_noise.label",description:"dataPipeline:definitions.random_noise.description",category:"augment",scope:"train",properties:{std:.03},modalities:["tabular","sequence","image"]},
];

const stage:Record<DataNodeCategory,number>={source:0,inspect:1,curate:2,split:3,transform:4,augment:5,output:6};
const modalityFor=(task:TaskId)=>task.startsWith("image")?"image":task.startsWith("sequence")?"sequence":task.startsWith("text")?"text":"tabular";
const make=(definition:Definition):DataPipelineNode=>({id:crypto.randomUUID(),type:definition.type,label:definition.label,description:definition.description,category:definition.category,scope:definition.scope,properties:{...definition.properties},enabled:true});
const outputNode=(dataset:DatasetSummary):DataPipelineNode=>({id:"output",type:"output",label:"dataPipeline:definitions.output.label",description:"dataPipeline:definitions.output.description",category:"output",scope:"all",enabled:true,locked:true,properties:{batchSize:Number(dataset.options?.batchSize||32),workers:0,pin_memory:true}});

export function defaultDataPipeline(task:TaskId,dataset:DatasetSummary):DataPipeline{
  const modality=modalityFor(task);const sourceLabel=dataset.source==="huggingface"?"dataPipeline:definitions.source.huggingFaceLabel":dataset.source==="synthetic"?"dataPipeline:definitions.source.syntheticLabel":"dataPipeline:definitions.source.importedLabel";const nodes:DataPipelineNode[]=[{id:"source",type:"source",label:sourceLabel,description:dataset.sourcePath||dataset.description,category:"source",scope:"all",enabled:true,locked:true,properties:{}},make(DEFINITIONS[0])];
  if(modality==="tabular"||modality==="sequence")nodes.push(make(DEFINITIONS[3]));if(modality==="image")nodes.push(make(DEFINITIONS[8]));nodes.push(outputNode(dataset));return {schemaVersion:1,revision:0,nodes};
}

function hydratePipeline(task:TaskId,dataset:DatasetSummary):DataPipeline{
  const source=dataset.pipeline||defaultDataPipeline(task,dataset);let nodes=source.nodes.filter(node=>node.type!=="split");if(!nodes.some(node=>node.type==="source"))nodes.unshift(defaultDataPipeline(task,dataset).nodes[0]);
  const output=nodes.find(node=>node.type==="output");nodes=nodes.filter(node=>node.type!=="output");nodes.push({...outputNode(dataset),...output,locked:true,properties:{...outputNode(dataset).properties,...output?.properties}});nodes[0]={...nodes[0],locked:true};return {...source,nodes};
}

export default function DataPipelineEditor({task,dataset,onApply}:{task:TaskId;dataset:DatasetSummary;onApply:(pipeline:DataPipeline)=>Promise<void>}){
  const { t } = useTranslation(["dataPipeline","common"]);
  const initial=hydratePipeline(task,dataset);const [pipeline,setPipeline]=useState<DataPipeline>(initial);const [selectedId,setSelectedId]=useState(initial.nodes[1]?.id||"source");const [libraryOpen,setLibraryOpen]=useState(false);const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(!dataset.pipeline);const [draggedId,setDraggedId]=useState<string|null>(null);const [,setPortalReady]=useState(0);
  useEffect(()=>{const next=hydratePipeline(task,dataset);setPipeline(next);setSelectedId(current=>next.nodes.some(node=>node.id===current)?current:next.nodes[1]?.id||"source");setDirty(!dataset.pipeline)},[dataset.id,dataset.revision,task]);useEffect(()=>setPortalReady(1),[]);
  const modality=modalityFor(task);const selected=pipeline.nodes.find(node=>node.id===selectedId);const available=DEFINITIONS.filter(def=>(def.modalities.includes("all")||def.modalities.includes(modality))&&!def.excludeTasks?.includes(task)&&!(def.unique&&pipeline.nodes.some(node=>node.type===def.type)));const localDiagnostics=useMemo(()=>validatePipeline(pipeline,t),[pipeline,t]);const diagnostics=[...(pipeline.diagnostics||[]),...localDiagnostics];
  const setNodes=(change:(nodes:DataPipelineNode[])=>DataPipelineNode[])=>{setPipeline(value=>({...value,nodes:change(value.nodes),diagnostics:[]}));setDirty(true)};const update=(id:string,patch:Partial<DataPipelineNode>)=>setNodes(nodes=>nodes.map(node=>node.id===id?{...node,...patch}:node));
  const add=(def:Definition)=>{const node=make(def);setNodes(nodes=>{const copy=[...nodes];copy.splice(copy.length-1,0,node);return copy});setSelectedId(node.id);setLibraryOpen(false)};const remove=(id:string)=>{setNodes(nodes=>nodes.filter(node=>node.id!==id));setSelectedId("source")};
  const move=(id:string,direction:-1|1)=>setNodes(nodes=>{const copy=[...nodes],index=copy.findIndex(node=>node.id===id),target=index+direction;if(index<=0||target<=0||target>=copy.length-1)return nodes;[copy[index],copy[target]]=[copy[target],copy[index]];return copy});
  const reorder=(from:string,to:string)=>setNodes(nodes=>{const fromIndex=nodes.findIndex(node=>node.id===from),toIndex=nodes.findIndex(node=>node.id===to);if(fromIndex<=0||toIndex<=0||fromIndex===nodes.length-1||toIndex===nodes.length-1)return nodes;const copy=[...nodes];const [item]=copy.splice(fromIndex,1);copy.splice(toIndex,0,item);return copy});
  const apply=async()=>{if(localDiagnostics.some(item=>item.level==="error"))return;setBusy(true);try{await onApply({...pipeline,revision:pipeline.revision+1});setDirty(false)}finally{setBusy(false)}};const inspectorHost=document.getElementById("data-node-inspector");
  return <><article className="panel pipeline-panel"><div className="pipeline-toolbar"><span className="eyebrow">{t("dataPipeline:eyebrow")}</span><div className="pipeline-actions"><span className={dirty?"revision dirty":"revision"}>{t("dataPipeline:revisionUnapplied",{revision:pipeline.revision,unappliedText:t("dataPipeline:unapplied")})}</span><button className="secondary" onClick={()=>setLibraryOpen(true)}><Plus/> {t("dataPipeline:addNode")}</button><button className="primary" disabled={busy||!dirty||localDiagnostics.some(item=>item.level==="error")} onClick={apply}>{busy?<RefreshCw className="spin"/>:<Check/>} {t("dataPipeline:apply")}</button></div></div>
    <div className="pipeline-canvas" role="list" aria-label={t("dataPipeline:ariaPipeline")}>{pipeline.nodes.map((node,index)=><div className="pipeline-node-wrap" key={node.id}>{index>0&&<i className={`pipeline-edge ${node.scope==="train"?"train":""}`}/>}<button draggable={!node.locked} onDragStart={event=>{setDraggedId(node.id);event.dataTransfer.effectAllowed="move"}} onDragOver={event=>{if(!node.locked)event.preventDefault()}} onDrop={()=>{if(draggedId)reorder(draggedId,node.id);setDraggedId(null)}} role="listitem" className={`pipeline-node ${selectedId===node.id?"selected":""} ${node.enabled?"":"disabled"}`} onClick={()=>setSelectedId(node.id)}>{!node.locked&&<GripVertical className="node-grip"/>}<span>{iconFor(node)}</span><small>{t(`dataPipeline:categories.${node.category}` as any)}</small><strong>{t(node.label as any)}</strong><em>{node.scope==="train"?t("dataPipeline:scope_train"):node.enabled?t("dataPipeline:scope_all"):t("common:disabled")}</em></button></div>)}</div>
    <div className="pipeline-diagnostics">{diagnostics.length?diagnostics.slice(0,2).map((item,index)=><button key={`${item.nodeId}-${index}`} className={item.level} onClick={()=>item.nodeId&&setSelectedId(item.nodeId)}>{item.level==="error"?<AlertCircle/>:<Eye/>}<span>{translateBackendError(item.message)}</span></button>):<div className="pipeline-ok"><CheckCircle2/><span><strong>{t("dataPipeline:pipelineValid")}</strong> {t("dataPipeline:readyToGenerate")}</span></div>}</div></article>
    {libraryOpen&&<div className="pipeline-popover-backdrop" onMouseDown={()=>setLibraryOpen(false)}><section className="pipeline-popover" onMouseDown={event=>event.stopPropagation()}><header><div><span className="eyebrow">{t("dataPipeline:dataLibrary")}</span><h3>{t("dataPipeline:addTransformation")}</h3><p>{t("dataPipeline:compatibleOperations",{modality:t(`dataPipeline:modality_${modality}` as any)})}</p></div><button className="modal-close" onClick={()=>setLibraryOpen(false)}><X/></button></header><div className="pipeline-library">{available.map(def=><button key={def.type} onClick={()=>add(def)}><div className="library-node-preview"><span>{iconFor(def)}</span><small>{t(`dataPipeline:categories.${def.category}` as any)}</small><strong>{t(def.label as any)}</strong></div><div><strong>{t(def.label as any)}</strong><p>{t(def.description as any)}</p><em>{t(`dataPipeline:definitions.${def.type}.scope` as any)}</em></div></button>)}</div></section></div>}
    {inspectorHost&&selected&&createPortal(<NodeInspector node={selected} dataset={dataset} onUpdate={update} onMove={move} onRemove={remove}/>,inspectorHost)}</>;
}

function NodeInspector({node,dataset,onUpdate,onMove,onRemove}:{node:DataPipelineNode;dataset:DatasetSummary;onUpdate:(id:string,patch:Partial<DataPipelineNode>)=>void;onMove:(id:string,direction:-1|1)=>void;onRemove:(id:string)=>void}){
  const { t } = useTranslation(["dataPipeline","common"]);
  return <div className="node-inspector-content"><div className="pipeline-inspector-title"><span>{iconFor(node)}</span><div><small>{t(`dataPipeline:categories.${node.category}` as any)}</small><h3>{t(node.label as any)}</h3></div></div><p>{t(node.description as any)}</p>{node.type==="output"&&<div className="dataset-contract"><span><small>{t("common:samples")}</small><strong>{dataset.samples}</strong></span><span><small>{t("common:input")}</small><strong>[{dataset.inputShape.join(", ")}]</strong></span><span><small>{t("common:output")}</small><strong>[{dataset.outputShape.join(", ")}]</strong></span></div>}{!node.locked&&<label className="pipeline-switch"><span>{t("dataPipeline:nodeActive")}</span><button className={node.enabled?"toggle on":"toggle"} onClick={()=>onUpdate(node.id,{enabled:!node.enabled})}><i/></button></label>}<div className="pipeline-properties">{Object.entries(node.properties).map(([key,value])=><PipelineProperty key={key} name={key} value={value} onChange={next=>onUpdate(node.id,{properties:{...node.properties,[key]:next}})}/>)}</div>{!node.locked&&<div className="pipeline-node-actions"><button title={t("dataPipeline:moveBefore")} onClick={()=>onMove(node.id,-1)}><ArrowUp/> {t("dataPipeline:before")}</button><button title={t("dataPipeline:moveAfter")} onClick={()=>onMove(node.id,1)}><ArrowDown/> {t("dataPipeline:after")}</button><button className="danger" onClick={()=>onRemove(node.id)}><Trash2/> {t("common:delete")}</button></div>}{node.locked&&<div className="locked-node-note"><Layers3/> {t("dataPipeline:lockedNodeNote",{position:t(`dataPipeline:position_${node.type==="source"?"start":"end"}` as any)})}</div>}</div>;
}

function PipelineProperty({name,value,onChange}:{name:string;value:string|number|boolean;onChange:(value:string|number|boolean)=>void}){
  const { t } = useTranslation(["dataPipeline","common"]);
  const label=t(`dataPipeline:properties.${name}` as any,name);
  if(typeof value==="boolean")return <label><span>{label}</span><button type="button" className={value?"toggle on":"toggle"} onClick={()=>onChange(!value)}><i/></button></label>;
  if(name==="mode")return <label><span>{label}</span><select value={String(value)} onChange={event=>onChange(event.target.value)}><option value="standard">{t("dataPipeline:options.mode.standard")}</option><option value="minmax">{t("dataPipeline:options.mode.minmax")}</option><option value="minmax_sym">{t("dataPipeline:options.mode.minmax_sym")}</option></select></label>;
  if(name==="method")return <label><span>{label}</span><select value={String(value)} onChange={event=>onChange(event.target.value)}><option value="bilinear">{t("dataPipeline:options.method.bilinear")}</option><option value="nearest">{t("dataPipeline:options.method.nearest")}</option><option value="bicubic">{t("dataPipeline:options.method.bicubic")}</option></select></label>;
  if(name==="channels")return <label><span>{label}</span><select value={String(value)} onChange={event=>onChange(Number(event.target.value))}><option value="3">{t("dataPipeline:options.channels.3")}</option><option value="1">{t("dataPipeline:options.channels.1")}</option></select></label>;
  return <label><span>{label}</span><input type={typeof value==="number"?"number":"text"} step="any" value={String(value)} onChange={event=>onChange(typeof value==="number"?Number(event.target.value):event.target.value)}/></label>;
}

function validatePipeline(pipeline:DataPipeline,t:TFunction){const result:NonNullable<DataPipeline["diagnostics"]>=[];const active=pipeline.nodes.filter(node=>node.enabled);if(active[0]?.type!=="source"||active.at(-1)?.type!=="output")result.push({level:"error",message:t("dataPipeline:validation.endpoints")});let last=0;for(const node of active){const current=stage[node.category];if(current<last&&node.type!=="output")result.push({level:"error",nodeId:node.id,message:t("dataPipeline:validation.outOfOrder",{label:t(node.label as any)})});last=Math.max(last,current);if(node.category==="augment"&&node.scope!=="train")result.push({level:"error",nodeId:node.id,message:t("dataPipeline:validation.trainOnly",{label:t(node.label as any)})})}return result}
function iconFor(node:Pick<DataPipelineNode,"type"|"category">){if(node.type==="resize")return <Maximize2/>;if(node.type==="center_crop")return <Crop/>;if(node.type==="random_rotate90")return <RotateCw/>;if(node.type==="convert_channels"||node.type==="color_jitter")return <Image/>;if(node.category==="source")return <Database/>;if(node.category==="inspect")return <Eye/>;if(node.category==="curate")return <Filter/>;if(node.category==="augment")return <Sparkles/>;if(node.category==="output")return <CheckCircle2/>;return <WandSparkles/>}
